### ISSUE TITLE
Add "Go to" shortcut

### ISSUE THREAD

**Issue by sloria** [glushchenko/fsnotes#885] opened 2020-05-10 19:28 UTC
**Describe your feature request**

An increasingly popular pattern in editor apps is the ability to fuzzy-find items with a keyboard shortcut (usually Cmd+P or Cmd+T). It would be useful to have something similar shortcut in FSNotes for fuzzy matching files and folders.

**Additional context**

As an example, here's what the Cmd+P menu looks like in Notion:

![Image 2020-05-10 at 3 21 50 PM](https://user-images.githubusercontent.com/2379650/81508416-08675a80-92d2-11ea-8292-9806970da9f2.png)

I'm unsure whether FSNotes should search...

1. Everything
2. Folders and files
3. Folders only
4. Folders and tags

Personally, I'd like the ability to jump to folders quickly, so I'd rather have number 3 or 4 if it meant that the search would be noticeably faster than 1 and 2, but this is not a strong preference.

**Comment by gingerbeardman** [comment] 2020-05-11 09:38
I do this already using my Alfred workflow: https://github.com/glushchenko/fsnotes/wiki/Alfred-Workflow

**Comment by sloria** [comment] 2020-05-11 13:05
I'm not using Alfred. I prefer to use a hotkey to focus a given application (configured with BetterTouchTool) then use the application's "go-to" shortcut. Example: `Option+n,Cmd+P`.

**Comment by gingerbeardman** [comment] 2020-05-11 15:37
My point is: you can help yourself and get this done right now using third party tools. Or you can wait for it to be added to the app - which could potentially be forever if it's not a popular feature request.

Dupe of #402

**Closed by gingerbeardman** 2020-05-11 15:37 UTC
Labels: request

**Comment by sloria** [comment] 2020-05-11 15:53
Ah, I missed that existing issue--sorry for the noise. I'll 👍 that then.

I appreciate you sharing workaround, even though I don't plan to use it.

**Comment by gingerbeardman** [comment] 2020-05-11 16:01
No worries at all!
