### ISSUE TITLE
Couple of oddities

### ISSUE THREAD

**Issue by jeff-h** [glushchenko/fsnotes#113] opened 2018-02-02 02:54 UTC
When in an RTF note, if you indent a line by pressing tab, the font, colour and background colour all change unexpectedly (perhaps something to do with a markdown feature?).

Also, when you're at the end of a note and press the down arrow, under some circumstances the scrollbar appears and the document jumps up and down by a line, all from just pressing the down arrow key repeatedly. You can see this at the end of the screencast below.

![2018-02-02 15_51_41](https://user-images.githubusercontent.com/841871/35714399-3e74c172-0831-11e8-87f0-a6399f276825.gif)

**Comment by greendog99** [comment] 2018-02-16 16:13
FYI, 1.2.9 still has the font/color/background issue when starting a line with tab (looks like it's trying to do code highlighting even though I have that turned off and this is not code).

**Comment by greendog99** [comment] 2018-02-24 18:52
The strange scrolling behavior is still happening in 1.2.11. Here's a more in-depth screencast showing the issue. All I'm doing is pressing the down arrow key once per second. You can see that when the cursor gets to the bottom of the screen, additional down arrow presses alternate between scrolling all the way back to the top, and then back to current position.

![9a8u2orcls](https://user-images.githubusercontent.com/30274/36633837-804f96d0-1961-11e8-8710-0268b4623162.gif)

**Comment by glushchenko** [comment] 2018-02-24 20:09
Please try build 105

**Comment by jeff-h** [comment] 2018-02-24 20:16
Fixed! 😃 Thanks so much for all your hard work.

**Comment by greendog99** [comment] 2018-02-24 20:20
Thanks! Build 105 resolves the scrolling issue I just shared above. However, it does still suffer from the original one-line scrolling issue that @jeff-h demonstrated when he opened this issue: "when you're at the end of a note and press the down arrow, under some circumstances the scrollbar appears and the document jumps up and down by a line, all from just pressing the down arrow key repeatedly."

That's far less annoying than the issue where it scrolled back to the top of the page, but it's still "odd". In doing a little testing, that issue seems to happen (in build 105) when the fsnotes window height does not match a multiple of the line height. I.e. if the bottom line of the note is only half visible in the window, this back-and-forth one line jump seems to happen when using the up/down arrows. If I resize the window to exactly match the line height, the problem goes away. Hope this helps!

**Comment by jeff-h** [comment] 2018-02-24 23:43
Strange. I can't replicate the original problem in 1.2.11 (105). It really does seem fixed for me.

However, I'm re-opening this, since you do still see the issue.

**Comment by greendog99** [comment] 2018-02-24 23:44
I'll try to capture a screencast tonight on (105)...

**Comment by greendog99** [comment] 2018-02-25 01:07
The odd one-line scrolling at the bottom of the note only seems to happen if there is an URL somewhere higher in the note, out of view. In this video I keep pressing down arrow until I reach the bottom and it works fine. Then I go near the top of the note and add an URL. Then back to the bottom and the odd scrolling happens when I press down arrow. Thanks for looking into it!

![fya2xlxfg5](https://user-images.githubusercontent.com/30274/36636922-c74a1f36-1995-11e8-9734-b72e21822840.gif)

**Comment by glushchenko** [comment] 2018-02-25 06:45
Build 106 should fix it. Please checkout.

**Comment by greendog99** [comment] 2018-02-25 15:23
Build 106 Fixed that specific test case, but I'm still running into a similar problem in many other files. It seems that the longer the note is, the worse the problem. Try loading the attached note, go to the bottom, and then use the up arrow to start moving up the note. Every press of the up arrow jumps the note around. Thanks again!
[test.txt](https://github.com/glushchenko/fsnotes/files/1756249/test.txt)

**Comment by gingerbeardman** [comment] 2018-02-25 15:31
@greendog99 I can't reproduce this using your test file. Does it happen on a new/guest account?

**Comment by greendog99** [comment] 2018-02-25 15:40
@gingerbeardman can you confirm that FSNotes recognized and formatted the URL at the top of the test file? If I undo the link formatting, the file works fine. I'll create a new account on my Mac and capture a screen recording there...

**Comment by greendog99** [comment] 2018-02-25 15:48
@gingerbeardman I can NOT reproduce on a new test account on my Mac. Not sure what that means, but I'll keep experimenting and report back if I can find a reliable way to reproduce it...

**Comment by gingerbeardman** [comment] 2018-02-25 15:50
Yes, the link is formatted and clickable. https://youtu.be/SmbbNbrrJzs

If it doesn't happen on a new test account then it means it's something to do with the settings/prefs/apps you have running on your account.

Try logging in holding down shift to prevent your startup apps running, and see if it happens then. A painful process of elimination is ahead.

**Comment by greendog99** [comment] 2018-02-25 16:27
Preventing startup apps didn't help. I copied my notes folder over to my test account and the problem showed back up. I deleted all notes except the test note and it still happened. I ran `sum` on the test note in the working and failing folders and they have the same checksum. Not sure why it's happening using one notes folder but not the other.

However, I have been able to easily reproduce a possibly related issue using the new test account. When I create my test note and view it, my H1 header is displayed in bold. When I scroll past it with the cursor, it changes to plain text and the height of the lines around it changes. When I go to the bottom, I don't have the scrolling problem. Video below.

Interestingly, on my note that has the scrolling problem, the H1 text is never shown as bold on screen... it's always just plain text. I'll keep experimenting, but I thought the bold issue might be a clue and might be reproducible by others. 
![v1](https://user-images.githubusercontent.com/30274/36643821-797f65b4-1a16-11e8-9152-c214452d8b94.gif)

**Comment by gingerbeardman** [comment] 2018-02-25 16:41
Syntax highlighting needs some attention.

the document has different behaviour if you name it .txt or .md and I don't think this should be the case?

**Comment by greendog99** [comment] 2018-02-25 16:46
Correct. Here's a longer screencast showing the difference. This is on a new account on my Mac.
![ss-20180225-104540](https://user-images.githubusercontent.com/30274/36643994-0d831b5a-1a19-11e8-80ea-ca28076d085c.jpg)
![gif2](https://user-images.githubusercontent.com/30274/36643996-1287a0d0-1a19-11e8-9308-f9e199aedf5e.gif)

**Comment by gingerbeardman** [comment] 2018-02-25 16:49
I can reproduce that funky behaviour.

Let's see what @glushchenko says, as I don't think we can solve this ourselves.

**Comment by glushchenko** [comment] 2018-02-25 19:52
Thanks @gingerbeardman @greendog99, i reproduced all bugs. Will be fixed on the next week.

**Comment by glushchenko** [comment] 2018-02-26 17:14
Guys, last build (107), should fix all oddities.

**Comment by greendog99** [comment] 2018-02-26 18:25
Looks good to me. Thanks!!

**Closed** 2018-02-27 07:25 UTC
Labels: done
