### ISSUE TITLE
Redesign user interface on iOS

### ISSUE THREAD

**Issue by dylanseeger** [glushchenko/fsnotes#1518] opened 2023-04-29 20:21 UTC
**Describe your feature request**
Below are a handful of suggestions for refining and modernizing the user interface of FSNotes on iOS, bringing it closer to the polish of FSNotes for Mac and other system apps.

I've included rough mockups of the main Library and Editor screens. Please let me know should you have any questions or if you think anything can be improved upon.

### Library
- Display top heading in a style consistent with system apps (large heading that scales on scroll)
- A "Search and create" field should be visible at the top of the Library list for easy access
- The “Settings” icon should be removed from the navigation bar and moved to the bottom of the sidebar
- List item dividers should extend to the right edge of the screen, consistent with system apps like Messages
- Move the note counter to the bottom center of the screen
### Editor
- A new toolbar at the bottom of the Editor view should include icons for quickly searching and composing notes without returning to the Library
  - This bar would only display when the keyboard is not in use (like Notes.app)

## Aesthetics
- Replace all icons with SF Symbols
  - I can make recommendations for each icon, if needed
  - All icons should match their Mac counterparts
- Replace all “Ellipses” modals with modern, compact dropdown menus (like Notes.app)
- Change navigation bar color to #FFFFFF (or #000000 when dark mode is enabled)
- Change sidebar color to #F7F7F7
- Change "+" button color to #00A9E0 to match new app icon and remove its outline

## Miscellaneous
- The "+" button shouldn't activate until the user's finger is lifted from the screen
- Add option to hide note previews in the Library for increased information density
- Add option to hide date from notes list
- Update “Projects” terminology to “Folders”

![2023-04-29 Mobile Library UI Mockup - FSNotes](https://user-images.githubusercontent.com/2807899/235322508-3c542344-8d10-4fcc-a2f6-c421bb992019.png)

![2023-04-29 Mobile Editor UI Mockup - FSNotes](https://user-images.githubusercontent.com/2807899/235355327-ccb65150-dede-4b9f-bf5d-1cf9ce57448f.png)

**Additional context**

**Comment by nth-chile** [comment] 2023-05-02 02:14
If we're talking about a redesign, we should really consider Apple's SwiftUI. It's an amazing developer experience, especially for apps that are built for both iOS and MacOS. Supports light and dark mode out of the box. And easy for people to contribute to without adding bugs, because people who know SwiftUI will be familiar with the code

**Comment by gingerbeardman** [comment] 2023-05-02 11:29
The only problem with SwiftUI, IMHO, is that it is limited to recent versions of macOS/iOS so excludes a whole bunch of users.

**Comment by gingerbeardman** [comment] 2023-05-02 14:32
Sadly it's not that black and white, SwiftUI features have been introduced gradually so you need to be careful which you use to maintain compatibility. 

iOS is perhaps easier, yes, but a lot of macOS apps I want to use specifically require macOS 13.1 Ventura, for example.

**Comment by nth-chile** [comment] 2023-05-02 14:45
Ok, I didn't know that. In any case, I'm all for @dylanseeger 's idea to gravitate the design towards Apple's system UI. I like all of these suggestions.

**Comment by dylanseeger** [comment] 2023-05-11 12:25
Wow — it's really happening! Looking great.

A few small things I noticed:
- New note "+" icon should be solid white (not transparent)
- Overall size of the new note button could be ~25% larger
- Divider line between notes should extend to the right edge of the screen (like Messages.app)

I also think "Settings" should be relegated to the sidebar, rather than as an icon at the top, as we shouldn't encourage endless fiddling.

Thanks for all your work on this. What a difference!

**Comment by gingerbeardman** [comment] 2023-05-11 13:07
Great progress! How exciting.

I've installed FSNotes on iOS.

**Comment by nth-chile** [comment] 2023-05-11 15:21
It looks great!

**Comment by nth-chile** [comment] 2023-05-11 15:25
If the system ui idea gets applied to desktop, FSNotes might start to look like Finder, which I think would be cool

<img width="380" alt="Screenshot 2023-05-11 at 11 16 55 AM" src="https://github.com/glushchenko/fsnotes/assets/22358233/d2284875-6dde-4797-8ba7-4362d8cce005">

.

.

Ulysses is taking a similar approach

![](https://ulysses.app/assets/start/en/devices@2x.png)

**Comment by glushchenko** [comment] 2023-05-18 22:33
Hi to all, guys, i want to release FSNotes 6 this month. If there are any requests about UI after the last beta, I will be glad to hear them.

FSNotes 6 Build 257 available in TestFlight.

## Couple of screens

Long tap menu:

![IMG_1547](https://github.com/glushchenko/fsnotes/assets/1089917/08af390a-2a59-493a-bd40-68cba9b1b503)

Multiple selection and toolbar:

![IMG_1548](https://github.com/glushchenko/fsnotes/assets/1089917/f494b1bc-212d-47b2-8f1d-57daaa431d7f)

Menu popover:

![IMG_1550](https://github.com/glushchenko/fsnotes/assets/1089917/d11f10df-7e54-4e28-9bbb-d1908aea863a)

**Comment by nth-chile** [comment] 2023-05-18 22:35
Wow, looks like you've been busy! How do I add it To TestFlight?

**Comment by glushchenko** [comment] 2023-05-18 22:39
@nth-chile i sent the invitation to the email from your profile. Check TestFlight please.

**Comment by glushchenko** [comment] 2023-05-18 22:43
@dylanseeger 

> The dividing line between the notes should reach to the right edge of the screen (like in Messages.app)

I'll try that later, I don't know how yet.

> I also think "Settings" should be moved to the sidebar rather than as an icon at the top, since we shouldn't encourage endless fiddling around.

It used to be that way, but people don't find settings there, I had to move it to a visible location.

**Comment by dylanseeger** [comment] 2023-05-19 00:27
Fantastic update, @glushchenko. I love how the "Search or create" field sticks to the top of the notes list when scrolling.

My suggestions after a couple hours of testing:

## Critial Bugs
- Pull to refresh causes all notes to disappear
  - Is there a need for pull to refresh at all?

## Notes List
- Reverse note list swipe options such that "Delete" is on the right, per system standards
- Update "More" swipe option list to match the new style of other "..." buttons
- Change "UnPin" to "Unpin"
- Add ability to hide note body preview in the notes list (possibly in a future release)
- Changing the editor font size shouldn't affect the size of text in the notes list
- Allow dragging allow "Select" checkboxes to select multiple notes quickly

## Library
- When selecting a folder from the sidebar/library, the navigation bar should only state the name of the folder, not “Project “Folder Name””
- Visibility options for folders are greyed out and cannot be changed
- Update sidebar icons to SF Symbols (tray, note.text, archivebox, trash, folder, tag)
- Indent subfolders in sidebar
  - Consider adding the ability to collapse subfolders (probably in a future release)
- We should eventually consider alternatives to the sidebar, such as the "Folders" screen in Notes.app, for a more native feel and to allow for more organizational features, such as collapsing subfolders and greater discoverability of new folder creation — if we do this, I'd move the settings icon there, too

## Menus
- Capitalize all context menu items, per system standards
  - "Copy plain text" should be "Copy Plain Text"
  - "View settings" should be "View Settings"
  - Change "Date created" to "Change Creation Date"
- Refine "Change Creation Date" popup
  - Add heading so users know where they are
  - Center the calendar widget
  - Replace the "+" button with "Update" text

## Settings
- Change "Files Format" to "Files"
- Enable "Autocorrection" by default
- Change "Spell Checking" to "Check Spelling"
- All settings should be in title case; i.e. "Code Block Live Highlighting" and "Use Inline Tags"
- "Advanced > Sidebar" should be "Advanced > Library"
- Change “App Icon” to “Icon”
- Change “Dylan Seeger” icons to “Modern” — the credit in “Thanks to” is enough for me!
- Where did this "Mars" icon come from?
- Change "Homepage" to "Website" and "Thanks to" to "Thanks"
- When selecting a folder from "Settings > Folders," the navigation bar should only state the name of the folder, not "Project "Folder Name""

## Miscellaneous
- Rename options when long-pressing app icon to “New Note,” “Save Clipboard,” and “Search or Create”
- Increase speed when selecting search icon on editor screen; the animations feel a bit janky
- Add tag suggestion popup (possibly in a future release)
- Change enter key on search from "go" to "create"

Some big items and many more small details which add up to a lot. Subtle inconsistencies can cause a conscious or subconscious drop in user confidence, so it’s important to get the balance right. We’re so close and I sincerely appreciate the hard work you’ve put into this. Amazing how far we've come!

**Comment by gingerbeardman** [comment] 2023-05-19 01:12
It feels like a different app already, it will be an amazing update when finished. 👏

**Comment by nth-chile** [comment] 2023-05-19 01:27
Good suggestions @dylanseeger. Also great idea to put the sidebar on a new screen, I wouldn't've thought of that. The sidebar button is already on the top left, just replace it with a back button and have it go to its own screen. It would buy some real estate for more stuff (like the settings icon)

**Comment by dylanseeger** [comment] 2023-05-19 13:53
A few additional observations:

- When using the search field after scrolling the notes list, results should begin at the top, so the user doesn't have to scroll up to see them
- Typing a query with no matches after scrolling the notes list causes search bar to change its position
- Remove "Also supports plaintext and RTF files." from website — replace with "Supports plain text files."
- Consider changing the marketing name in the App Store from "FSNotes Manager (Powerful Markdown Editor)" to "FSNotes (Remarkably fast plain text notes)

**Comment by glushchenko** [comment] 2023-05-22 07:55
@dylanseeger almost all of this fixed with the exception of:

> Update "More" swipe option list to match the new style of other "..." buttons

It's technically difficult.

> Update sidebar icons to SF Symbols (tray, note.text, archivebox, trash, folder, tag)

There are no encrypted folders and analogues in the apple SF Symbols, the current ones were drawn by my wife in the same style.

> Visibility options for folders are greyed out and cannot be changed

I can't do it yet, maybe I'll hide it later.

> Indent subfolders in sidebar

That's a big and complicated question, not for this update.

> Add tag suggestion popup (possibly in a future release)

Don't understand what it is?

> Increase speed when tapping the search icon in the editor; these animations feel a bit janky

I haven't found a solution yet.

--

Thank you so much for such a detailed feedback, you are very helpful.

**Comment by dylanseeger** [comment] 2023-05-27 17:41
@glushchenko Some notes on the pre-release build:

- There are a handful of typos/inconsistencies in the intro dialog:
	- Close button should be the new blue color
	- Any reference to Apple's "HID" should be "human interface guidelines" as many users may not understand the abbreviation
	- Thanks for your kind shout out — the comma after my name should be removed
	- Git: Add colon (:) after "you can learn about it here"
	- Encrypted folders: "now I'm pull the same" should be "now I'm adding the same"
	- Application icons: "I have it looks like this:" should be "Mine is set to look like this:"
	- Improvements to the editor: "Even more actions directly from the editor" should be "Even more actions are available directly within the editor"
	- Solver core: "This is a calculator that now works in previews, you can read more about its functions here" should be "This calculator now displays in Preview mode. Read more about its functions here:"
	- Fixes: "New bugs was added of course :)" should be "New bugs may have been added, of course." or remove this line entirely
- The app's loading/splash screen shows the white logo, even when dark mode is enabled
- The search field in the notes list extends a bit too far to the left — it should align with the left side of the heading
- In dark mode on iPhone, the top delineator (the line between search and notes list) is not uniform in color — the left edge is darker than the rest of the line

Congratulations — looking forward to the release!

**Comment by amarendra** [comment] 2023-05-27 22:27
iOS - v 6.0.0 build 263

### Preview mode bug (can create a new ticket if needed or additional details)

- If one note gets its "preview only" toggled ON (i.e. cannot be edited by just one click/touch - i.e. the crossed eye icon showing) - all other notes also go to "preview only" mode.
- And vice-versa - if one note gets "preview only" toggled OFF (i.e. can be edited now - i.e. normal eye icon showing) - all other notes also go into "edit mode" mode.

Expected behaviour:

- Edit or preview only mode toggle ought to be for individual notes - preview mode changing to ON or OFF for one note should not change whatever this setting was for other notes

Additional suggestion/request:
- Preferably the preview mode can also be such that the note is not editable at all unless the eye icon is clicked/touched again
    - i.e. by mistake double tapping a note should not toggle its preview mode i.e should not make it editable
    - one use case example: a user might want a note just for READ purpose (or copy whole or parts of this note by selecting text) and never or very rarely editing - e.g. I have few notes, like a note where my IDs and some serials are listed, I would not want to edit that note accidentally - I mostly just copy info from that note
        - Once in a while I would add some data to that note but never edit existing IDs/etc because they never change
        - At the same time I do not want to or need to lock this note with a password - Just keep "non editable". 

### Search icon on note bug

- Clicking the search icon on a any individual note opens the search among all notes i.e. it opens the notes list with search bar focussed 

Expected behaviour:
- The search icon/option on an individual note should only search that note and not all the notes

Additional suggestion/request:
- Might be a good idea to not keep search and new note (+) icons on the note screen bottom - it takes a lot of real estate on the screen especially at the bottom - it can be integrated on the top bar as well

**Comment by glushchenko** [comment] 2023-05-28 10:48
@dylanseeger my english is definitely poor, thanks. 
@amarendra you propose to make preview like in macOS, save state per note, not global?

App released today, so i will try to implement your suggestions later. Thanks to all!

https://fsnot.es/fsnotes6-for-ios/

**Closed by glushchenko** 2023-05-28 10:48 UTC
Labels: request

**Comment by dylanseeger** [comment] 2023-05-28 11:31
@glushchenko No worries. If you’d like, I would be happy to help write or proofread copy for future releases. I only speak English and am quite picky.

**Comment by amarendra** [comment] 2023-11-27 15:24
> @amarendra you propose to make preview like in macOS, save state per note, not global?

I guess this wasn't done. Or maybe there is a feature request created somewhere. Should I create  one if it's not?

**Comment by gingerbeardman** [comment] 2023-11-27 15:43
@amarendra please create a new issue
