### ISSUE TITLE
Subfolders being shown as folders

### ISSUE THREAD

**Issue by ksdomino** [glushchenko/fsnotes#1135] opened 2021-06-17 08:40 UTC
**the bug**
On the mac version: After setting the storage location (in preferences) to a folder of my choice , the pane on the left shows all subfolders as folders. This makes it very hard to stay organised as there is no nesting, which is fine if nesting is not a feature but at least those subfolders should not be showing (or maybe there should be an option to "hide subfolders")
screengrabs link below.

**To Reproduce**
1. Make sure fsnotes is not open
2. Create a folder and put a couple of subfolders inside
3. Open fsnotes, Go into 'preferences' and set the storage location to the folder you created in step 1
4. Apply/Ok and you'll see the bug in effect. 

**Expected behavior**
It should only show a list of folders in the storage location, not the millions of subfolders in a non-nested way.
**Actual behavior**
It shows every subfolder as a folder which makes it very difficult to work with the app when many subfolders exist in the notes system.

**Workaround**
None that I know of 

**Supporting Files**
I have put 2 screenshots at:
https://imgur.com/a/6cWopMD

**Desktop**
 - OS: macOS
 - OS version: Catalina 10.15.7 
 - FSNotes version: Version 4.9.13

**Comment by gingerbeardman** [comment] 2021-06-18 09:10
Dupe of long-standing #188

**Comment by ksdomino** [comment] 2021-06-18 10:58
Sorry for the dupe. I did search before posting. Anyways I posted a possible solution/idea to your thread that can be coded when the developer can address this.

**Comment by gingerbeardman** [comment] 2021-06-18 11:22
@ksdomino dupes are not a problem at all, in fact they are useful because they give weight to the original issue

**Comment by glushchenko** [comment] 2021-06-21 07:41
Of course you can hide subfolders:

```
xattr -w "es.fsnot.hidden.dir" true path/To/DirName
xattr -w "es.fsnot.hidden.dir" false path/To/DirName
```

**Closed** 2021-07-28 15:54 UTC
Labels: bug, done, duplicate
