### ISSUE TITLE
Folding Headers / Outlining

### ISSUE THREAD

**Issue by gdup213** [glushchenko/fsnotes#1216] opened 2021-10-05 12:56 UTC
**Describe your feature request**

Text under headers to be able to fold/unfold.

create foldable outlines with indenting like an outliner

**Additional context**
Add any other related information here. macOS or iOS?
mac and ios

**Comment by shvechikov** [comment] 2022-02-07 20:19
Looks like a duplicate of https://github.com/glushchenko/fsnotes/issues/132 ?

**Comment by gingerbeardman** [comment] 2022-02-07 23:04
Please add your vote to #132 @gdup213

**Closed** 2022-02-07 23:03 UTC
Labels: request
