### ISSUE TITLE
iOS app requires restart to fully sync

### ISSUE THREAD

**Issue by sven-gh** [glushchenko/fsnotes#620] opened 2019-06-11 09:03 UTC
When creating a new folder or tag on Mac then these changes only show up on iOS for me after I first killed/restarted the iOS app.

iOS 12.3.1
FSNotes 2.6.2

Mac 10.14.5
FSNotes 3.3.1

edit: I meant that forcing a refresh by swiping down on the notes list isn't enough to show the new folder or tag - need to kill/restart app instead

**Comment by hellonoko** [comment] 2019-06-23 05:18
Same issue I believe.

FSNotes: 3.3.1 on macOS 10.14.5 (18F132)
FSNotes: 2.7.1 on iOS 12.3.1 on iPad

Created a new folder "KITCHEN REMODEL" in FSNotes on macOS.
Created a new rtf inside the folder "KITCHEN REMODEL".
 
Folder did not show up on iPad in FSNotes folders list.
Pulling down panel did not refresh folders lists.
Did hard close of FS Notes.
Folder showed up on restart.

**Comment by stephencweiss** [comment] 2019-11-22 02:29
@sven-gh, @hellonoko - out of curiosity, I'm still trying to get sync to work at all. Do you need to use the App Store versions for sync?

**Comment by hellonoko** [comment] 2019-11-22 02:30
As far as I know it seems to work now. 

I use the App store versions.

**Comment by stephencweiss** [comment] 2019-11-22 14:07
@hellonoko -- did you have to do anything special? connect to an iCloud account at any point?

**Comment by stephencweiss** [comment] 2019-11-22 14:15
Interesting - I got it to work iOS -> MacOS by changing the default storage on Mac to the iCloud Drive. 

MacOS files aren't showing up in iOS though...? Maybe just a timing issue, but I closed the app and refreshed based on this thread's issue... still nothing.

**Comment by hellonoko** [comment] 2019-11-22 15:30
I can't recall. I had to setup my iCloud drive at first. At first it was behaving oddly but lately seems ok, although I have not been using FSNotes a lot lately so I can't say for sure.

**Comment by jasonekratz** [comment] 2020-01-22 23:54
This issue is still occurring with both the latest iOS build from the app store and 4.0.18 on the Mac. Creating folders on either requires me to restart the apps to get the view refreshed. iCloud is syncing properly because I see the folder updates in Finder. Interestingly editing documents seems to work just fine. I don't know much about how this all works but it seems that there is some refresh problem in the MVC setup.

**Comment by glushchenko** [comment] 2020-11-16 22:29
Fixed in 4.0 for iOS

**Closed by glushchenko** 2020-11-16 22:29 UTC
Labels: bug

**Comment by joehanna** [comment] 2021-11-28 03:02
This is not fixed in **4.8.5 build 228**. I am new to FSNotes and have been setting it all up on the Mac. iOS does not pick up new folders unless the app is completely restarted (clear from memory and re-open). Once iOS app is open and "alive" (active on screen) and new folders appear instantly. The issue is if the app is in the background and then wakes up, it doesn't catch up on folder changes.
