### ISSUE TITLE
Pasting a todo item renders it as plain text

### ISSUE THREAD

**Issue by samer** [glushchenko/fsnotes#902] opened 2020-05-22 11:31 UTC
**Describe the bug**
When pasting a TODO item, it is rendered in plain text 

**To Reproduce**
1. Create a todo (cmd+T)
2. Highlight and copy it
3. Paste it

**Expected behavior**
- [ ] The new todo item would be rendered as a checkbox

**Actual behavior**
The new todo item is rendered as plain text (`- [ ]`)

**Workarounds**
Switching to another note and back renders it correctly.

**Supporting Files**
<img width="233" alt="Screenshot 2020-05-22 at 13 30 56" src="https://user-images.githubusercontent.com/554078/82663709-7bf15c00-9c30-11ea-9bf9-fc033cb2d78d.png">

**Comment by sloria** [comment] 2020-05-25 18:27
I think this is a duplicate of https://github.com/glushchenko/fsnotes/issues/895

**Comment by samer** [comment] 2020-05-25 19:13
Thanks @sloria. I think they are related, but not really dupes. Either way, it's good to have those two issues linked as the fix would probably fix them both.

**Closed** 2021-05-28 17:09 UTC
Labels: bug, done
