### ISSUE TITLE
Allow automatic file naming based on first line of file

### ISSUE THREAD

**Issue by dequeued0** [glushchenko/fsnotes#1222] opened 2021-10-11 23:14 UTC
**Describe your feature request**

1Writer (on iOS) has a nice feature for new files that I think would be a very nice enhancement for FSNotes.

The first line of a new file is used to name the file. Once the file is saved with that name, the file name doesn't change unless you explicitly rename the file. (In 1Writer, this feature is activated with the "auto file naming" setting.)

This seems much easier for everyday use than naming files based on timestamps.

**Additional context**

This is *not* the same thing as the "First line as title" option. (In fact, that option would almost definitely be turned off for most people using this proposed feature.) The first line is only used to determine the file name for new files. Afterwards, it's just a regular file name.

**Comment by glushchenko** [comment] 2021-10-12 06:44
Have you ever opened the settings?

**Comment by dequeued0** [comment] 2021-10-14 02:23
> Have you ever opened the settings?

:-(

I have opened the settings many times and I have tested multiple options. That is why I mentioned the "First line as title" option.

The "First line as title" option hides all of the filenames for my existing notes. After a note is named, it shouldn't matter what the first line of the note is.

I thought that the "Auto Rename By Title" option might be relevant, but it does not name files based on the first line of the title. If that is what it is supposed to do, it may not be working correctly on the Mac platform. File names are still getting a hexadecimal filename even after the first line is completed.

If there is another option that I should be looking at, please let me know.

Thanks.

**Comment by dequeued0** [comment] 2021-10-14 02:48
To add some information:

I understand that if I create a new note using the "Search or create" field, the name used there becomes the first line and is used for the filename. However, if I create a new note using the button to the right of the "Search or create" (the square button with a pen/pencil) on the upper right) then the first line does not become the filename.

In 1Writer, right when you click + to start a note and start typing, the first line becomes the title and any time you edit the first line, the file is automatically renamed. That is the feature I am requesting.

**Comment by dequeued0** [comment] 2021-10-15 06:48
I'm using the Mac version of FSNotes as I mentioned here:

> I thought that the "Auto Rename By Title" option might be relevant, but it does not name files based on the first line of the title. If that is what it is supposed to do, it may not be working correctly on the Mac platform. File names are still getting a hexadecimal filename even after the first line is completed.

**Comment by dequeued0** [comment] 2021-10-15 08:28
I am running macOS 11.6.

I have added all of my settings to this album: https://imgur.com/a/7k2UJ81

The first animated image in the album shows how to reproduce it on my system. FSNotes **never** renames the file based on the first line.

I also tested FSNotes 4.10.2 yesterday and it has the same issue for me.

What additional information do you need?

**Comment by glushchenko** [comment] 2021-10-15 09:01
I understand what you are talking about, but I don’t think it needs to be fixed. In any case, after editing, old notes will lose data from their titles if use auto rename option.

**Comment by hrvojepilic** [comment] 2021-12-19 17:41
Hi,

I'm with @dequeued0 here with the same situation. I just switched to FSNotes, loving it so far. But this things really bugs me. 

I have "Auto Rename By Title" for files naming in settings, but when I create new note, I end up with something like this: "02056E29 B1AE 4D0C 8F43 7649E9C4E1A7".

Coming from multiple editors from the past and having more than 2k notes, I also need this working. 
I use filenames as titles.
Am I doing something wrong or is this isn't possible yet?

How do you usually set the name of the titles, just writing it manually or? 

I would be cool if it can be auto generated maybe from the first line before first save or auto renamed from YAML meta data as I usually use title and id there, so end up with a filename like this: "note title YYYYMMDDHHSS" format.

Thanks

**Comment by gingerbeardman** [comment] 2021-12-19 20:02
I can reproduce this issue.

Perhaps this has regressed to not working? @glushchenko

**Comment by ksdomino** [comment] 2022-04-21 06:09
It has indeed regressed to not working. It was working 2 or 3 versions ago for me but no longer works.. I can post a youtube vid if needed.

**Comment by glushchenko** [comment] 2022-04-21 06:19
> It has indeed regressed to not working. It was working 2 or 3 versions ago for me but no longer works.. I can post a youtube vid if needed.

How to reproduce it? Works fine for me.

**Comment by ksdomino** [comment] 2022-04-21 06:49
> How to reproduce it? Works fine for me.

1. I uninstalled and reinstalled FSNOTES to attempt to fix it so that can be a first step in reproducing it.
2. I create a new note and put "test title 1" or something similar (without the quote marks obviously).
3. the note doesn't rename (I can visually tell it didn't rename because the bar at the top of the screen doesn't change (I will show all these better in the youtube vid I will post in a while).
4. I go into preferences and check the 2 options mentioned ( in the general tab, files naming is set to "auto rename by title", and in layout, "first line as title" is ticked.)
( I tested changing those options and all the other options work, but as of the last few versions, auto-renaming doesn't work for everyone).

**Comment by glushchenko** [comment] 2022-04-21 18:01
Hi all, finally y I found problem. Auto rename not working when "Scan inline tags" is disabled.

**Comment by ksdomino** [comment] 2022-04-21 21:13
> Hi all, finally I found problem. Auto rename not working when "Scan inline tags" is disabled. Fixed now.

Excellent, will look forward to a future release (where hopefully I can disable inline tag scanning and have first line renaming still working! Thanks so much for getting this sorted.

**Comment by glushchenko** [comment] 2022-04-21 21:17
I plan to release the update like always on Sunday. Thank you for bug report 🍻

**Comment by ksdomino** [comment] 2022-04-21 22:34
> I plan to release the update like always on Sunday. Thank you for bug report 🍻

Wow that's quick, Thanks so much and glad to help in whatever small way I can. Thanks again :)

**Comment by glushchenko** [comment] 2022-04-24 08:18
https://github.com/glushchenko/fsnotes/releases/download/5.4.0/FSNotes_5.4.0.zip

**Comment by schwantuschke** [comment] 2022-04-25 13:09
Unfortunately it still doesn't work for me :(
Whether "Scan inline tags" is enabled or not.

**Comment by ksdomino** [comment] 2022-04-25 13:12
Working fine here now. I updated using the apple store this morning and tested it.
Hopefully you get it fixed on yours too [schwantuschke](https://github.com/schwantuschke).
Could be another setting messing with it..did you put it back to defaults?

**Comment by schwantuschke** [comment] 2022-04-25 19:13
Ok. "auto rename by title" works only if "first line as title" is active. Doesn't it then make sense to make the functions in the settings window dependent on each other?

**Comment by ksdomino** [comment] 2022-04-25 20:43
Glad you got it sorted :) I too was wondering why that option "first line as title" even exists so I think you're right, they should  at least be put on the same tab/page ideally next to each other or if it doesn't do anything else then it should be removed/merged into a single item to avoid confusion for future users.

**Comment by xor-gate** [comment] 2022-04-29 08:56
I think this feature works, but it did automagicly rename my files which I did not expect. If I use the setting other than "Auto Rename By Title" it should not touch my filenames every again right? I'm now using the "Format: Untitled Note" setting.

**Closed** 2023-04-08 00:13 UTC
Labels: request, done
