### ISSUE TITLE
Inline tagging system picking up extraneous data

### ISSUE THREAD

**Issue by koyedele** [glushchenko/fsnotes#725] opened 2019-10-31 21:19 UTC
**Describe the bug**
I have Ruby code enclosed in code tags but because I have `#{one}` within a String in the Ruby code, a new tag is created for `{one}`. Is it possible to not scan code samples for tags?

**To Reproduce**
1. Create a new note
2. Create a code block using three backticks and specify the language as Ruby, for example

<pre>
```ruby
watermelon = 'code'
"Here's some ruby #{watermelon}"
```
</pre>
3. Notice that a new tag with name `{watermelon}` is created

**Expected behavior**
Scanning for inline tags should respect some boundaries for Markdown text especially code samples that are clearly defined

**Actual behavior**
Scanning for inline tags does not respect code boundaries so a lot of useless tags get created

**Workaround**
Disable scanning for inline tags

**Supporting Files**
<img width="394" alt="Screen Shot 2019-10-31 at 2 13 10 PM" src="https://user-images.githubusercontent.com/13141314/67986668-c6ee4800-fbe8-11e9-8e2e-285e529676e6.png">
<img width="147" alt="Screen Shot 2019-10-31 at 2 13 24 PM" src="https://user-images.githubusercontent.com/13141314/67986680-cb1a6580-fbe8-11e9-9e36-13a6da38f1c9.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.14.6
 - FSNotes version: 4.0.2

**Additional context**

**Comment by glushchenko** [comment] 2019-10-31 21:21
You can add #notags tag for disable tags

**Comment by koyedele** [comment] 2019-10-31 21:25
Thanks for the quick turnaround! If I do that, I do not get tags at all. I do want to be able to tag notes, but I also want to be able to have code samples in there. It seems that the scanning of inline tags doesn't support both.

**Comment by glushchenko** [comment] 2019-11-06 14:40
You proposal is code blocks checking in tags scanner?

**Comment by koyedele** [comment] 2019-11-06 20:46
I would say yes. 

<pre>
`This #{var} should not become a tag`
</pre> 

and

<pre>
```
This #{var} should not become a tag either
```
</pre>

Apparently, it affects Latex blocks as well. So

<pre>
$ a \dot b #some_random_thing 
</pre>

should not become a tag and

<pre>
$$
This #var should not show up as a tag either
$$
</pre>

I notice that it seems FSNotes doesn't support `<pre>` blocks. On GitHub, if I want to write the literal three back-tick characters without starting a code block (like I've been doing in this issue post), I can surround the text with `<pre></pre>` and it will come out unmodified. The point is, if FSNotes ever starts supporting that or if it supports some other way, then we'd need to make sure that we don't search those fenced blocks for tags as well.

**Comment by isao** [comment] 2019-11-06 22:55
Hi @glushchenko great app, thanks for your work.

I just filed #733 which I just realized is somewhat a dupe of this bug.

My suggestion there is to treat a valid tag as a `#` followed by at least one letter, preferably something like this regex: `/^#[a-zA-Z][a-zA-Z0-9\-]+$/`

Right now I have tons of accidental tags for my imported notes. In my case I have many notes  which contain misc log output statements, bash, or ruby...

**Comment by Aetles** [comment] 2019-11-10 16:45
Yeah, I have a lot of notes with hex colors (like #FF0000) and I would prefer if they were not picked up.

**Comment by glushchenko** [comment] 2019-11-13 16:54
Numbers and hex will bi excluded from 4.0.7, code blocks I think a little bit later.

**Comment by GeoJunkie** [comment] 2020-01-21 10:46
I'm afraid I might add another level of complexity, but I'll ask anyway. I use Slack extensively and many of my notes refer to Slack channels, which all start with a `#` (e.g. the main `#announcements` channel). 

Would it be possible to have a "not a tag" option to exclude specific strings from being marked as tags?

**Comment by glushchenko** [comment] 2020-01-21 11:14
Add #notags

**Closed** 2020-11-25 05:46 UTC
Labels: bug, request
