### ISSUE TITLE
Unable to edit selected note after starting FSNotes

### ISSUE THREAD

**Issue by peavine** [glushchenko/fsnotes#107] opened 2018-01-29 00:55 UTC
I've encountered an issue with version 1.2.7. This happens when I:

1) select a note in the note-list; 
2) quit FSNotes; 
3) start FSNotes; 
4) Without changing the selected note, click in the main window to begin editing.

When I do the above, I expect the cursor to be where I click in the main window, but it isn't. No matter how many times I click, nothing happens. If I select another note and click in main window, or if I tab to the main window, then the cursor is there as expected.

BTW, I'm running Sierra with all updates. I also experienced the above issue with 1.2.5 but not 1.2.2 (which, of course, does not remember the selected note).

Thanks

peavine

**Comment by jeff-h** [comment] 2018-01-29 01:22
FWIW — I don't seem to have this problem... but I do have a similar one; if I do the following:

* select a note and place the text cursor somewhere in it
* hide FSNotes (cmd-H)
* bring it back with the keyboard shortcut

...the original note is there as expected but the cursor cannot be placed anywhere in the note. I have to select a different note in order to have an active cursor again. I usually select a different note then back to the original, but that's kind of annoying.

**Comment by glushchenko** [comment] 2018-01-29 06:14
Hm, this fixed in 1.2.4, and now i can't reproduce bug.

**Comment by peavine** [comment] 2018-01-29 16:53
I did some additional troubleshooting and discovered this issue was my doing.

I use one-line applescripts along with the Fastscripts utility to launch apps, and when I started using launchpad to start FSNotes the issue went away. I now use an alias with Fastscripts to start FSNotes and all is well.

Sorry for the false alarm.

**Closed** 2018-01-29 17:24 UTC

**Comment by jeff-h** [comment] 2018-01-30 00:54
![demo1](https://user-images.githubusercontent.com/841871/35542470-114f2b24-05c5-11e8-90ab-752604cf1f75.gif)
Anyone else get this?

**Comment by glushchenko** [comment] 2018-01-30 14:37
@jeff-h 

Fixed in 1.2.8 https://github.com/glushchenko/fsnotes/releases/tag/1.2.8

**Comment by peavine** [comment] 2018-01-31 14:26
After installing 1.2.8, I went back to starting FSNotes as I had before (Fastscripts and Applescript) and this works fine now. Thanks.
