### ISSUE TITLE
[REQ] - title and file name automatically take on the first line on the note.

### ISSUE THREAD

**Issue by hellonoko** [glushchenko/fsnotes#418] opened 2018-11-21 04:32 UTC
It would be nice if when I create a new note and type in something like 'grocery list' the title  and file name of the note becomes whatever i typed in on the first line.

It would also be nice if a double click of the notes title activated the title editing dialog.

**Comment by gingerbeardman** [comment] 2018-11-21 09:29
Agreed.

Dupe of #279

**Comment by peavine** [comment] 2018-11-21 14:13
Renaming a note by double-clicking the note name at the top of the editor window is an excellent idea. 

As to the other matter, and FWIW, I wrote in the thread referenced by gingerbeardman that:

"In the past I have used note apps in which the note name was automatically set to the first heading in the note, and I never found this to be helpful. If this feature is implemented, I hope there will be an option to disable it in preferences."

**Comment by buddax2** [comment] 2018-11-21 14:20
I implemented double-clicking today here #419

**Comment by glushchenko** [comment] 2018-11-21 21:34
Merged, thanks @buddax2

**Comment by glushchenko** [comment] 2018-11-21 21:36
"Title from first line and preview from second" will be roll out with next update.

**Comment by peavine** [comment] 2018-11-24 14:07
I just installed FSNotes 2.5 and the new feature to rename a note by double-clicking the note name works great. @buddax2 does nice work. Also, thanks for including a projects-view setting whether to use the first line of a note as the note title.

**Closed** 2018-11-27 19:21 UTC
Labels: done
