### ISSUE TITLE
Random colorization of text in preview mode

### ISSUE THREAD

**Issue by ruffkat** [glushchenko/fsnotes#470] opened 2019-01-25 16:46 UTC
Using the latest app store version, text in preview mode now renders with random colorization:

![image](https://user-images.githubusercontent.com/845997/51759669-639a1d00-208e-11e9-97d4-831c0e21f583.png)

**Comment by quinncomendant** [comment] 2019-01-25 23:51
I've noticed similar issues. Here's a screenshot of a small note I created, which contains some pasted text copied from a web page. The result is a white background in the two lines I pasted (the first two lines of the note), and even more weird, is the yellow background. Grey is my default note background color. It's like the style from the text of the website has been copied over the display in FSNotes. Don't know where the yellow comes from, it's not a yellow I use or have seen anywhere. 

<img width="558" alt="screen shot 2019-01-25 at 14 01 27" src="https://user-images.githubusercontent.com/6884276/51778608-45e9a980-20c8-11e9-88c1-9a555b13c41f.png">

**Comment by glushchenko** [comment] 2019-01-29 19:11
Fixed in 2.7.4

**Comment by quinncomendant** [comment] 2019-01-30 21:03
FSNotes 2.7.4 and 2.7.5: Markdown list items appear bold when they shouldn't:

<img width="200" alt="screen shot 2019-01-30 at 13 53 35" src="https://user-images.githubusercontent.com/6884276/52012297-d6950080-249f-11e9-9941-1a4f2d46dfb8.png">

This is only occurring in one note, in which I did copy-paste some text from a website, so I think it's related to this issue – but maybe not? I can't reproduce the issue in a new note. Only this note is corrupted. Quit and relaunch FSNotes doesn't help.

[Here's a video to demonstrate the problem](https://github.com/glushchenko/fsnotes/files/2814417/FSNotes.-.markdown.bold.lists.mov.zip)

**Comment by glushchenko** [comment] 2019-01-30 21:12
>FSNotes 2.7.4 and 2.7.5: Markdown list items appear bold when they shouldn't: ...

@quinncomendant can you provide file and steps for reproduce?

**Comment by quinncomendant** [comment] 2019-01-31 00:54
I'm not able to reproduce this issue in a new note; it only appears to happen in existing notes. 

Besides the bold in the Markdown notes, I'm also experiencing the white background problem again:

<img width="309" alt="screen shot 2019-01-30 at 18 39 25" src="https://user-images.githubusercontent.com/6884276/52022442-88dbc080-24be-11e9-927b-c2f7a79d7800.png">

Perhaps you can reproduce the problem in one of your existing notes:

1. Set your note background color to grey.
2. Go to [this page on aa.com](https://www.aa.com/i18n/customer-service/contact-american/reservations-and-ticket-changes.jsp).
3. Select and copy a phone number (e.g., `800-433-7300`).
4. Paste it at the end of a paragraph in an existing note.

**Comment by glushchenko** [comment] 2019-02-04 19:19
Please checkout FSNotes 2.8.0

**Closed** 2019-02-06 15:29 UTC
Labels: done
