### ISSUE TITLE
 iOS editor frequently makes the cursor jump to the bottom of the file when typing

### ISSUE THREAD

**Issue by willxie** [glushchenko/fsnotes#1678] opened 2024-01-06 11:00 UTC
### Description

It's pretty frustrating especially when there's no easy way to jump back to where I was typing in a large file. I turned off all all Editor rendering features and it still does the same thing. This very reproducible on my iPhone 13 mini. This can happen when my laptop is closed. I assume there should not be any opportunity for two devices updating the same file. 

![IMG_4232](https://github.com/glushchenko/fsnotes/assets/4821081/cb77e2bb-04a4-4126-901c-73ca64d59422)

### To Reproduce

1. Open any file
2. Start making edits
3. cursor jumps to the end of the file mid sentence as I was typing

### FSNotes version

6.2.1 build 276

### macOS/iOS version

17.1.2

**Comment by nth-chile** [comment] 2024-01-06 14:02
It is frustrating! I have iPhone 13 mini as well

**Comment by glushchenko** [comment] 2024-01-06 15:27
@nth-chile can you reproduce it too?

**Comment by nth-chile** [comment] 2024-01-06 15:56
Yes, but it doesn't happen all the time. I'll try to pay attention to see how to reproduce

**Comment by willxie** [comment] 2024-01-08 12:25
I tried to find a reproducible example using random texts. I was not able to. However, in my personal notes, it happens frequently. The characteristics of my notes are:
- most notes are long-ish, say 800 words
- i use a lot of bullet points and links
- no images. All other markdown features are used sparingly if at all.

**Comment by nburyak** [comment] 2024-01-17 10:50
Not sure, if it's the same issue. On MacOS I have also jumping cursor. Happens all the time but I can't come up with an explanation for such a behavior:

https://github.com/glushchenko/fsnotes/assets/2462403/80d00325-3edd-4c92-9535-9dd6ab2d8e52

**Comment by glushchenko** [comment] 2024-01-18 00:47
> Not sure, if it's the same issue. On MacOS I have also jumping cursor. Happens all the time but I can't come up with an explanation for such a behavior. 
> 
> 
> 
> In the screen recording below I only typed text, but the cursor tried to jump to the beginning of the line all the time:
> 
> 
> 
> https://github.com/glushchenko/fsnotes/assets/2462403/80d00325-3edd-4c92-9535-9dd6ab2d8e52
> 
> 
> 
> Version: `6.6.6 (610)`
> 
> macOS: `14.2.1 (23C71)`

Where do you store your notes? Try the default storage.

**Comment by nburyak** [comment] 2024-01-18 09:22
> Where do you store your notes? Try the default storage.

Hi @glushchenko, I'm using the default storage. I tried changing it to a different one and then back to default but it didn't solve the issue. 
Eventually, I've managed to find the exact steps to reproduce and created a [separate issue for it](https://github.com/glushchenko/fsnotes/issues/1683).

**Comment by gingerbeardman** [comment] 2024-01-23 14:49
I'm getting this. Only when using Gboard keyboard.

**Comment by gingerbeardman** [comment] 2024-02-16 18:11
This has driven me so crazy today. So much that I'm now using a different text editor on iOS.

**Comment by amarendra** [comment] 2024-02-17 18:56
This has been happening on both Mac and iOS for quite sometime. But I am not able to find the exact steps either.

I noticed it happens when I stop typing for sometimes and let there be a noticeable gap. But sadly not always. Sometimes it just goes the beginning of line, paragraph, note randomly. Sometimes it does that while still typing and not stopped.

it also moves to the end of the file/note sometimes. This is really difficult to deal with as it messes up a lot of text, more so if typing fast.

**Comment by glushchenko** [comment] 2024-02-18 00:38
@gingerbeardman can you test build 6.2.3 from testflight?

**Comment by gingerbeardman** [comment] 2024-02-18 01:23
Somehow I'm no longer on the TestFlight. Please email me a new link

**Comment by gingerbeardman** [comment] 2024-02-20 00:04
> @gingerbeardman can you test build 6.2.3 from testflight?

Initial testing seems to show it's fixed in the TestFlight version

**Closed** 2024-02-20 11:56 UTC
Labels: bug

**Comment by gingerbeardman** [comment] 2024-02-27 01:40
Whilst this is improved, instead of jumping to the bottom and staying there the new version flicks quickly to the bottom and then returns to the current position. It's really annoying because you're looking at the text when it happens. But at least I can keep editing. 

So, I don't think this is really truly fixed.

**Comment by glushchenko** [comment] 2024-02-27 20:53
There are several options, I can prevent the open note from reloading at all. But then no changes will be received during synchronization. If I make this as a separate option? Does this only happen on iOS?

**Comment by nth-chile** [comment] 2024-02-27 21:14
Is there a way to help prevent user from editing a note that hasn't been synchronized? It would help prevent the merge conflicts mentioned in #1700. Can it sync in the background when the app is minimized? And if the app is terminated, then when you launch it, it opens with no note selected?

**Comment by glushchenko** [comment] 2024-02-27 21:31
> Is there a way to help prevent user from editing a note that hasn't been synchronized? It would help prevent the merge conflicts mentioned in #1700. Can it sync in the background when the app is minimized? And if the app is terminated, then when you launch it, it opens with no note selected?

How can I know if my notes have been synchronized or not? For example in Dropbox or Google Drive or iCloud Drive? Implement all existing clouds?

**Comment by nth-chile** [comment] 2024-02-27 21:47
When you open the app from a minimized state, it sometimes shows an older state of the note and then flashes to the new one. If we could avoid that, it might prevent conflicts

**Comment by gingerbeardman** [comment] 2024-02-29 13:17
So the issue is that as I am typing the note is constantly reloading? Because the note is receiving a synchronisation from other devices? But the note I am working on has only just been created on my iPhone, it does not exist on any other devices.

Hmm, I think the syncing logic is not ideal.

Pausing this behaviour for some seconds would be a workaround, but I feel that if the flicker/jump still happens it's not really a solution. Why does the note need to sync at all whilst i'm editing it?

**Comment by nth-chile** [comment] 2024-02-29 13:22
I don't know how much sync is responsible for the cursor jump because the cursor jump sometimes happens repeatedly on every autosave

**Comment by glushchenko** [comment] 2024-03-10 20:52
Yes, reloading happens only in one case, when CloudDriveManager receives updated date of note file, and that date greater than local modification date.

**Comment by gingerbeardman** [comment] 2024-03-11 02:30
Then I have no idea why my note is constantly updating and reloading.

**Comment by glushchenko** [comment] 2024-03-11 02:50
This is a very interesting question as to why it just works for me. Everything seems to be standard, time syncs by ntp, APFS file system. What else could be breaking modification time?
