### ISSUE TITLE
Fix bulleted list text indentation

### ISSUE THREAD

**Issue by scottbickell** [glushchenko/fsnotes#947] opened 2020-07-13 22:57 UTC
**Describe your feature request**

I would like to see the left alignment of text to be inside the bulleted list. The issue shows when the line length wraps to a new line, and the left margin is at the same level as the bullet instead of the text above and/or below. 

**Additional context**
This is from macOS

![bullets2](https://user-images.githubusercontent.com/6173095/87361818-4aa75500-c52a-11ea-84d2-04663c6e2604.png)

**Comment by sloria** [comment] 2020-07-15 13:41
I believe this is a duplicate of https://github.com/glushchenko/fsnotes/issues/774

**Comment by glushchenko** [comment] 2021-07-11 11:10
Please test https://github.com/glushchenko/fsnotes/releases/tag/5beta1

**Comment by sloria** [comment] 2021-07-11 14:43
Just gave it a try. Looks great!

**Closed** 2021-08-22 09:12 UTC
Labels: request, done
