### ISSUE TITLE
Inline math rendering does not work

### ISSUE THREAD

**Issue by saf-dmitry** [glushchenko/fsnotes#950] opened 2020-07-14 14:24 UTC
**Describe the bug**
Inline math rendering does not work.

Source:

![Screenshot 2020-07-14 at 16 07 52](https://user-images.githubusercontent.com/30050534/87437019-12694a80-c5ee-11ea-85e2-6d584d69c810.png)

Preview:

![Screenshot 2020-07-14 at 16 07 34](https://user-images.githubusercontent.com/30050534/87437033-17c69500-c5ee-11ea-8471-f96a21bebfad.png)

**Expected behavior**
Inline math should be rendered in the preview.

**Actual behavior**
Inline math rendering does not work.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.14.6
 - FSNotes version: 4.4.0

**Comment by glushchenko** [comment] 2020-07-14 14:25
Safronov, please stop assign me.

**Comment by saf-dmitry** [comment] 2020-07-14 14:31
> Safronov, please stop assign me.

Sorry, the assignment happens automatically every time when I open new bug/issue.

**Comment by glushchenko** [comment] 2020-07-19 10:25
Documentation updated, you should use $$ or (( )), thanks for report.

**Comment by saf-dmitry** [comment] 2020-07-19 13:35
Just a question: What is a problem to use single `$`s to delimit inline math like in `$a \ne 0$`? Many popular Markdown processors like pandoc or MultiMarkdown adhere to this quite common syntax.

**Comment by glushchenko** [comment] 2020-07-19 16:34
In case of dollar symbol usage i have too many false positive bug reports, like:

https://github.com/glushchenko/fsnotes/issues/799

**Comment by glushchenko** [comment] 2020-07-19 16:36
> > Safronov, please stop assign me.
> 
> 
> 
> Sorry, the assignment happens automatically every time I open a new bug/issue.

Now its clear, i did not see what it is in template.

**Comment by saf-dmitry** [comment] 2020-07-20 11:01
> In case of dollar symbol usage i have too many false positive bug reports

Pandoc uses simple [heuristics](https://github.com/jgm/pandoc/issues/2976#issuecomment-225398171) to properly detect inline math inside dollar signs:

> You can have spaces inside `$...$`, just not at the very beginning or end.
> 
> If we allowed spaces after the opening `$` or before the closing `$`, we'd capture things like
> 
>     It costs $4 or $5.
> 
> as math. LaTeX can allow the spaces, because in LaTeX the `$` can only indicate math mode. In Markdown many `$`s are just `$`s, and we need heuristics to tell the difference. The rules about initial and final spaces are the heuristics.

So this would mean `$a + b$` is perfectly file, just don't use `$ a + b $`.

My experience (many years of authoring Markdown documents containing _a lot_ of math) is conform to other pandoc users' experience, that this actually works very reliable. I think, other Markdown parsers just follow the same rule. Therefore, I would vote for using `$` as inline math delimiters, since it is widely accepted among other Markdown flavors and Markdown writing apps.

**Comment by felixkreuk** [comment] 2020-11-02 08:14
Is this issues going to be resolved? I tend to agree with @saf-dmitry. Seems to me that the bug in #799 is not a bug but incorrect use of the $$ syntax. Also, it can be resolved by previewing without Latex rendering.

**Comment by saf-dmitry** [comment] 2020-11-23 13:06
If the `$...$` delimiter syntax for inline math is currently not supported, please fix the documentation here (`$a \ne 0$`):

![Screenshot 2020-11-23 at 13 40 37](https://user-images.githubusercontent.com/30050534/99964596-d4e2ae00-2d93-11eb-96ab-cbfc0b6e0f17.png)

Nevertheless, I still hope it will be supported in the future, mainly for the sake of compatibility with other applications and Markdown parsers.

**Comment by saf-dmitry** [comment] 2020-12-03 13:16
Alternatively, I would suggest using LaTeX syntax `\(...\)`, which is way more compatible to other Markdown applications and parsers.

**Closed** 2021-05-09 13:39 UTC
Labels: bug, done

**Comment by torralbofco** [comment] 2021-06-05 20:16
I agree with @saf-dmitry about supporting the `$...$` syntax for the inline math mode. At least the syntax `\(...\)` should be supported. I am a mathematician who would love to use fsnotes both in Mac and iPad but the lack of a compatible syntax with other markdown applications as well as with LaTeX itself is a real problem.
