### ISSUE TITLE
scroll past end

### ISSUE THREAD

**Issue by bnham** [glushchenko/fsnotes#649] opened 2019-07-21 22:31 UTC
Many editors have a feature which allow you to scroll past the last line of text (e.g. `editor.scrollBeyondLastLine` in VSCode). It'd be nice if FSNotes supported this as well.

**Comment by gingerbeardman** [comment] 2019-07-22 09:50
Agreed.

Dupe of #288

**Closed by gingerbeardman** 2019-07-22 09:50 UTC
