### ISSUE TITLE
Double-clicking the top of windows does not adhere to system settings

### ISSUE THREAD

**Issue by eyelessjerry** [glushchenko/fsnotes#1711] opened 2024-03-10 21:46 UTC
### Description

Double-clicking the top of windows does not adhere to system settings (as I believe was filed as a bug last year, but cannot find it now). It is horrible to have the window zoomed when using the classic macOS behaviour of minimizing the window to the dock (and/or app icon) – esp. when using that all the time in all other apps.

### To Reproduce

1. Go to System Settings and change the now (impracticable) default setting of zooming windows that are double-clicked to the more sensible previous setting of minimizing the window. (Desktop and dock)
2. Double-click the main FSNotes window and it will still be zoomed.
3. Expected behaviour won't happen as the window will be zoomed no matter what you do (only the small yellow button will work).

### Expected behavior

Upon double-clicking the head of the window it will be minimized to dock.

### FSNotes version

Version 6.7.0 (618)

### macOS/iOS version

macOS 14.4

**Comment by gingerbeardman** [comment] 2024-03-11 02:25
Dupe of #1594

**Closed** 2024-03-11 02:26 UTC
Labels: bug
