### ISSUE TITLE
[REQ] Organize notes on groups and subgroup

### ISSUE THREAD

**Issue by TofPlay** [glushchenko/fsnotes#362] opened 2018-09-29 15:38 UTC
It would be really great if we could organize notes in groups and subgroups 🙂

**Comment by gingerbeardman** [comment] 2018-09-29 16:09
Dupe of #188 

I agree 😄

**Comment by gingerbeardman** [comment] 2019-07-30 15:26
Closing as dupe

**Closed by gingerbeardman** 2019-07-30 15:26 UTC
Labels: duplicate, request
